# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_file_server.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16grpc_file_server.proto\"9\n\x11\x46ileUploadRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x11\n\tfile_data\x18\x02 \x01(\x0c\"6\n\x12\x46ileUploadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"(\n\x13\x46ileDownloadRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\" \n\tFileChunk\x12\x13\n\x0b\x64\x61ta_chunks\x18\x01 \x01(\x0c\"&\n\x11\x46ileDeleteRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"6\n\x12\x46ileDeleteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"A\n\x11\x46ileRenameRequest\x12\x15\n\rold_file_name\x18\x01 \x01(\t\x12\x15\n\rnew_file_name\x18\x02 \x01(\t\"6\n\x12\x46ileRenameResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xa0\x02\n\x0b\x46ileService\x12\x35\n\nUploadFile\x12\x12.FileUploadRequest\x1a\x13.FileUploadResponse\x12\x32\n\x0c\x44ownloadFile\x12\x14.FileDownloadRequest\x1a\n.FileChunk0\x01\x12\x35\n\nDeleteFile\x12\x12.FileDeleteRequest\x1a\x13.FileDeleteResponse\x12\x35\n\nRenameFile\x12\x12.FileRenameRequest\x1a\x13.FileRenameResponse\x12\x38\n\tListFiles\x12\x14.FileDownloadRequest\x1a\x13.FileUploadResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_file_server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILEUPLOADREQUEST']._serialized_start=26
  _globals['_FILEUPLOADREQUEST']._serialized_end=83
  _globals['_FILEUPLOADRESPONSE']._serialized_start=85
  _globals['_FILEUPLOADRESPONSE']._serialized_end=139
  _globals['_FILEDOWNLOADREQUEST']._serialized_start=141
  _globals['_FILEDOWNLOADREQUEST']._serialized_end=181
  _globals['_FILECHUNK']._serialized_start=183
  _globals['_FILECHUNK']._serialized_end=215
  _globals['_FILEDELETEREQUEST']._serialized_start=217
  _globals['_FILEDELETEREQUEST']._serialized_end=255
  _globals['_FILEDELETERESPONSE']._serialized_start=257
  _globals['_FILEDELETERESPONSE']._serialized_end=311
  _globals['_FILERENAMEREQUEST']._serialized_start=313
  _globals['_FILERENAMEREQUEST']._serialized_end=378
  _globals['_FILERENAMERESPONSE']._serialized_start=380
  _globals['_FILERENAMERESPONSE']._serialized_end=434
  _globals['_FILESERVICE']._serialized_start=437
  _globals['_FILESERVICE']._serialized_end=725
# @@protoc_insertion_point(module_scope)
