# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_file_server_pb2 as grpc__file__server__pb2


class FileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFile = channel.unary_unary(
                '/FileService/UploadFile',
                request_serializer=grpc__file__server__pb2.FileUploadRequest.SerializeToString,
                response_deserializer=grpc__file__server__pb2.FileUploadResponse.FromString,
                )
        self.DownloadFile = channel.unary_stream(
                '/FileService/DownloadFile',
                request_serializer=grpc__file__server__pb2.FileDownloadRequest.SerializeToString,
                response_deserializer=grpc__file__server__pb2.FileChunk.FromString,
                )
        self.DeleteFile = channel.unary_unary(
                '/FileService/DeleteFile',
                request_serializer=grpc__file__server__pb2.FileDeleteRequest.SerializeToString,
                response_deserializer=grpc__file__server__pb2.FileDeleteResponse.FromString,
                )
        self.RenameFile = channel.unary_unary(
                '/FileService/RenameFile',
                request_serializer=grpc__file__server__pb2.FileRenameRequest.SerializeToString,
                response_deserializer=grpc__file__server__pb2.FileRenameResponse.FromString,
                )
        self.ListFiles = channel.unary_stream(
                '/FileService/ListFiles',
                request_serializer=grpc__file__server__pb2.FileDownloadRequest.SerializeToString,
                response_deserializer=grpc__file__server__pb2.FileUploadResponse.FromString,
                )


class FileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenameFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=grpc__file__server__pb2.FileUploadRequest.FromString,
                    response_serializer=grpc__file__server__pb2.FileUploadResponse.SerializeToString,
            ),
            'DownloadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=grpc__file__server__pb2.FileDownloadRequest.FromString,
                    response_serializer=grpc__file__server__pb2.FileChunk.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=grpc__file__server__pb2.FileDeleteRequest.FromString,
                    response_serializer=grpc__file__server__pb2.FileDeleteResponse.SerializeToString,
            ),
            'RenameFile': grpc.unary_unary_rpc_method_handler(
                    servicer.RenameFile,
                    request_deserializer=grpc__file__server__pb2.FileRenameRequest.FromString,
                    response_serializer=grpc__file__server__pb2.FileRenameResponse.SerializeToString,
            ),
            'ListFiles': grpc.unary_stream_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=grpc__file__server__pb2.FileDownloadRequest.FromString,
                    response_serializer=grpc__file__server__pb2.FileUploadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FileService/UploadFile',
            grpc__file__server__pb2.FileUploadRequest.SerializeToString,
            grpc__file__server__pb2.FileUploadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/FileService/DownloadFile',
            grpc__file__server__pb2.FileDownloadRequest.SerializeToString,
            grpc__file__server__pb2.FileChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FileService/DeleteFile',
            grpc__file__server__pb2.FileDeleteRequest.SerializeToString,
            grpc__file__server__pb2.FileDeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RenameFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FileService/RenameFile',
            grpc__file__server__pb2.FileRenameRequest.SerializeToString,
            grpc__file__server__pb2.FileRenameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/FileService/ListFiles',
            grpc__file__server__pb2.FileDownloadRequest.SerializeToString,
            grpc__file__server__pb2.FileUploadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
