# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_file_server_v2.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19grpc_file_server_v2.proto\"9\n\x11\x46ileUploadRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x11\n\tfile_data\x18\x02 \x01(\x0c\"6\n\x12\x46ileUploadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\x11\x46ileDeleteRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"6\n\x12\x46ileDeleteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"$\n\x14MakeDirectoryRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"9\n\x15MakeDirectoryResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2{\n\x0b\x46ileService\x12\x35\n\nUploadFile\x12\x12.FileUploadRequest\x1a\x13.FileUploadResponse\x12\x35\n\nDeleteFile\x12\x12.FileDeleteRequest\x1a\x13.FileDeleteResponse2R\n\x10\x44irectoryService\x12>\n\rMakeDirectory\x12\x15.MakeDirectoryRequest\x1a\x16.MakeDirectoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_file_server_v2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEUPLOADREQUEST']._serialized_start=29
  _globals['_FILEUPLOADREQUEST']._serialized_end=86
  _globals['_FILEUPLOADRESPONSE']._serialized_start=88
  _globals['_FILEUPLOADRESPONSE']._serialized_end=142
  _globals['_FILEDELETEREQUEST']._serialized_start=144
  _globals['_FILEDELETEREQUEST']._serialized_end=182
  _globals['_FILEDELETERESPONSE']._serialized_start=184
  _globals['_FILEDELETERESPONSE']._serialized_end=238
  _globals['_MAKEDIRECTORYREQUEST']._serialized_start=240
  _globals['_MAKEDIRECTORYREQUEST']._serialized_end=276
  _globals['_MAKEDIRECTORYRESPONSE']._serialized_start=278
  _globals['_MAKEDIRECTORYRESPONSE']._serialized_end=335
  _globals['_FILESERVICE']._serialized_start=337
  _globals['_FILESERVICE']._serialized_end=460
  _globals['_DIRECTORYSERVICE']._serialized_start=462
  _globals['_DIRECTORYSERVICE']._serialized_end=544
# @@protoc_insertion_point(module_scope)
